In [77]:
import numpy as np

In [78]:
cvalue = [20.1,20.8,30,45.6,78]

In [79]:
c = np.array(cvalue)
print(c)

[20.1 20.8 30.  45.6 78. ]


In [81]:
print(c.dtype) #int arr[] = [1,2]
print(type(cvalue))

float64
<class 'list'>


In [84]:
#converting the values of celcius to fahrenhrit 

#in python
fvalue = [x*9/5 + 32 for x in cvalue]
print(fvalue)

#in numpy 
f = c*9/5 + 32
print(f)

[68.18, 69.44, 86.0, 114.08000000000001, 172.4]
[ 68.18  69.44  86.   114.08 172.4 ]


<img src="list_structure.png" style="float: left; height: 16em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="array_structure.png" style="float: right; height: 14em; margin-right: 1%; margin-bottom: 0.5em;">

In [87]:
#memory comparison
from sys import getsizeof 
lst = [24, 12, 57]
size_of_list_object = getsizeof(lst)   
size_of_elements = len(lst) * getsizeof(lst[0]) 
total_list_size = size_of_list_object + size_of_elements
print("Size without the size of the elements: ", size_of_list_object)
print("Size of all the elements: ", size_of_elements)
print("Total size of list, including elements: ", total_list_size)
# li = []
# print(getsizeof(li))

#for numpy array
a = np.array([24, 12, 57])
print("\n The size of numpy array", getsizeof(a))
# print(getsizeof(np.array([])))

Size without the size of the elements:  88
Size of all the elements:  84
Total size of list, including elements:  172
64

 The size of numpy array 108
96


In [91]:
#Time comparison
import time

size_of_vector = 100000
def pure_python():
    t1 = time.time()
    X = range(size_of_vector)
    Y = range(size_of_vector)
    Z = [X[i] + Y[i] for i in range(size_of_vector) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vector)
    Y = np.arange(size_of_vector)
    Z = X + Y
    return time.time() - t1

t1 = pure_python()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.05831503868103027 0.0003654956817626953
Numpy is in this example 159.5505544683627 faster!


In [99]:
#creation of arrays with evenly spaced values
# arange([start,] stop[, step], [, dtype=None])

arr1 = np.arange(8)
print(arr1)

# linspace(start, stop, num=50, endpoint=True, retstep=False)

arr2 = np.linspace(2,8,3, endpoint=False)
print(arr2)

#return step
samples, spacing = np.linspace(2,8,retstep=True)
print(samples)
print(spacing)

[0 1 2 3 4 5 6 7]
[2. 4. 6.]
[2.         2.12244898 2.24489796 2.36734694 2.48979592 2.6122449
 2.73469388 2.85714286 2.97959184 3.10204082 3.2244898  3.34693878
 3.46938776 3.59183673 3.71428571 3.83673469 3.95918367 4.08163265
 4.20408163 4.32653061 4.44897959 4.57142857 4.69387755 4.81632653
 4.93877551 5.06122449 5.18367347 5.30612245 5.42857143 5.55102041
 5.67346939 5.79591837 5.91836735 6.04081633 6.16326531 6.28571429
 6.40816327 6.53061224 6.65306122 6.7755102  6.89795918 7.02040816
 7.14285714 7.26530612 7.3877551  7.51020408 7.63265306 7.75510204
 7.87755102 8.        ]
0.12244897959183673


In [108]:
#Dimensional array in numpy

# scaler (zero dimension)
n = np.array(5)
print(np.ndim(n))
print(np.shape(n))

# vector (1-D)
n = np.array([2,3])
print(np.ndim(n))
print(np.shape(n))

# # matrics (2 or more dim)
n = np.array([[2,3,4,5],
              [3,4,7,9]])
print(np.ndim(n))
print(np.shape(n))

n = np.array([
              [[2,3,4],[4,5,6]],
              [[3,4,8],[9,8,5]],
              [[9,0,2],[1,2,1]]
            ])
print(np.ndim(n))
print(np.shape(n))

0
()
1
(2,)
2
(2, 4)
3
(3, 2, 3)


In [112]:
#indexing
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])

#print an element
print(A[1][1])
print(A[0,0])

# print entrire row
print(A[1,:])

# print entire column
print(A[:,0])

-7.8
3.4
[ 1.1 -7.8 -0.7]
[3.4 1.1 4.1]


In [114]:
# Slicing

# A[start:stop:step]
S = np.array([0, 1, 20, 3, 40, 5, 6, 7, 8, 9])
print(S[2:5])

[20  3 40]


In [116]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

<img src="slicing1.png",style="float: left; height: 15em; width:13em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="slicing2.png",style="float: left; height: 15em; width:13em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="slicing3.png",style="float: left; height: 15em; width:13em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="slicing4.png",style="float: left; height: 15em; width:13em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="slicing5.png",style="float: left; height: 15em; width:13em; margin-right: 1%; margin-bottom: 0.5em;">

In [126]:
#exercise
# print(A[0:3,2:])
# print(A[3:,:])
# print(A[:,-1])
print(A[0:-1:2,0::2])

[[11 13 15]
 [31 33 35]]


In [128]:
li  = [2,3,4,56,7,9]
s = li[1:3]
s[0] = 767
print(li)

[2, 3, 4, 56, 7, 9]


In [129]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
S = A[2:6]
S[0] = 22
print(A)

[ 0  1 22  3  4  5  6  7  8  9]


In [130]:
np.may_share_memory(A, S)

True

In [134]:
B = A.reshape(2, 5)
print(np.may_share_memory(A,B))
print(B)
B[0,0] = 98
print(A)

True
[[ 0  1 22  3  4]
 [ 5  6  7  8  9]]
[98  1 22  3  4  5  6  7  8  9]


In [138]:
# Creating array of ones, zero and empty

E = np.ones([2,3])
print(E)
F = np.ones((3,4),dtype=int)
print(F)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [139]:
Z = np.zeros((2,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [141]:
x = np.array([[2,5,18,14,4],[2,5,18,14,4]])
E = np.ones_like(x)
print(E)
Z = np.zeros_like(x)
print(Z)

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [154]:
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
#copying an array

x = np.array([[42,22,12],[44,53,66]])
y = x.copy()
z = np.copy(x)
x[0,0] = 1001
print(x)
print(y)
print(z)

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]
[[42 22 12]
 [44 53 66]]


In [162]:
# identity array
#  1) indentity funtion

a = np.identity(4,dtype =int)
print(a)

print("\n")
# 2) eye function
# eye(N, M=None, k=0, dtype=float)
b = np.eye(5, 4, k=0, dtype=int)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
