# dtype
<img src="europe_data.png" style="height:20em">

In [57]:
import numpy as np
i16 = np.dtype(np.int16)
print(i16)
lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]
A = np.array(lst, dtype=i16)
print(A)

int16
[[ 3  8  9]
 [ 1 -7  0]
 [ 4 12  4]]


In [58]:
dt = np.dtype([('density', np.int32)])
x = np.array([(393,), (337,), (256,)],
             dtype=dt)
print(x)
print("\nThe internal representation:")
print(repr(x))

[(393,) (337,) (256,)]

The internal representation:
array([(393,), (337,), (256,)], dtype=[('density', '<i4')])


In [59]:
print(x['density'])

[393 337 256]


In [60]:
dt = np.dtype([('country', 'S20'), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
population_table = np.array([
    ('Netherlands', 393, 41526, 16928800),
    ('Belgium', 337, 30510, 11007020),
    ('United Kingdom', 256, 243610, 62262000),
    ('Germany', 233, 357021, 81799600),
    ('Liechtenstein', 205, 160, 32842),
    ('Italy', 192, 301230, 59715625),
    ('Switzerland', 177, 41290, 7301994),
    ('Luxembourg', 173, 2586, 512000),
    ('France', 111, 547030, 63601002),
    ('Austria', 97, 83858, 8169929),
    ('Greece', 81, 131940, 11606813),
    ('Ireland', 65, 70280, 4581269),
    ('Sweden', 20, 449964, 9515744),
    ('Finland', 16, 338424, 5410233),
    ('Norway', 13, 385252, 5033675)],
    dtype=dt)
print(population_table[:4])

[(b'Netherlands', 393,  41526, 16928800)
 (b'Belgium', 337,  30510, 11007020)
 (b'United Kingdom', 256, 243610, 62262000)
 (b'Germany', 233, 357021, 81799600)]


In [61]:
print(population_table['density'])
print(population_table['country'])
print(population_table['area'])

[393 337 256 233 205 192 177 173 111  97  81  65  20  16  13]
[b'Netherlands' b'Belgium' b'United Kingdom' b'Germany' b'Liechtenstein'
 b'Italy' b'Switzerland' b'Luxembourg' b'France' b'Austria' b'Greece'
 b'Ireland' b'Sweden' b'Finland' b'Norway']
[ 41526  30510 243610 357021    160 301230  41290   2586 547030  83858
 131940  70280 449964 338424 385252]


In [62]:
np.savetxt("population_table.csv",
           population_table,
           fmt="%s,%d,%d,%d",           
           delimiter="*")

In [63]:
dt = np.dtype([('country', np.unicode, 20), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
x = np.genfromtxt("population_table.csv",
               dtype=dt,
               delimiter=",")
print(x)

[("b'Netherlands'", 393,  41526, 16928800)
 ("b'Belgium'", 337,  30510, 11007020)
 ("b'United Kingdom'", 256, 243610, 62262000)
 ("b'Germany'", 233, 357021, 81799600)
 ("b'Liechtenstein'", 205,    160,    32842)
 ("b'Italy'", 192, 301230, 59715625)
 ("b'Switzerland'", 177,  41290,  7301994)
 ("b'Luxembourg'", 173,   2586,   512000)
 ("b'France'", 111, 547030, 63601002)
 ("b'Austria'",  97,  83858,  8169929)
 ("b'Greece'",  81, 131940, 11606813)
 ("b'Ireland'",  65,  70280,  4581269)
 ("b'Sweden'",  20, 449964,  9515744)
 ("b'Finland'",  16, 338424,  5410233)
 ("b'Norway'",  13, 385252,  5033675)]


# numerical operation in numpy arrays

In [67]:
# using scalers
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst)
v = v + 2
print(v)

print(v * 2)

print(v - 1.38)

print(v ** 2)
print(v ** 1.5)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]
[ 8.   10.   19.8  10.6  17.8   4.22 24.6  29.8 ]
[ 2.62  3.62  8.52  3.92  7.52  0.73 10.92 13.52]
[ 16.      25.      98.01    28.09    79.21     4.4521 151.29   222.01  ]
[ 8.         11.18033989 31.14962279 12.2015163  26.55125232  3.06495204
 43.13776768 57.51477202]


In [68]:
# in python list
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
res = []
for val in lst:
    res.append(val + 2)
print(res)

res = [ val + 2 for val in lst]
print(res)

[4, 5, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]
[4, 5, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]


In [71]:
# Airthmetic operation in two arrays

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(B)
print('\n')
print(A)
print("Adding to arrays: ")
print(A + B)
print("\nMultiplying two arrays: ") #** this is not dot product:-component wise
print(A * (B + 1))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[11 12 13]
 [21 22 23]
 [31 32 33]]
Adding to arrays: 
[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]

Multiplying two arrays: 
[[22. 24. 26.]
 [42. 44. 46.]
 [62. 64. 66.]]


In [74]:
# Matrix multiplication
# C = np.reshape(9,1)
np.dot(A, B)

array([[36., 36., 36.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [76]:
print(np.dot(3, 4))
x = np.array([3])
y = np.array([4])
print(x.ndim)
print(np.dot(x, y))
x = np.array([3, -2])
y = np.array([-4, 1])
print(np.dot(x, y))

12
1
12
-14


In [87]:
x = np.array([3, -2, -5, -6, -7])
y = np.array([-4, 1, 6, 8, 8])
x = x.reshape(1,5)
y = y.reshape(5,1)
print(np.dot(y,x))

[[-12   8  20  24  28]
 [  3  -2  -5  -6  -7]
 [ 18 -12 -30 -36 -42]
 [ 24 -16 -40 -48 -56]
 [ 24 -16 -40 -48 -56]]


In [91]:
A = np.array([ [1, 2, 3], 
               [3, 2, 1] ])
B = np.array([ [2, 3, 4, -2], 
               [1, -1, 2, 3],
               [1, 2, 3, 0],
               [1, 2, 3, 0]])

if A.shape[-1] == B.shape[-2]:
    print(np.dot(A, B))

In [92]:
X = np.array(
    [
     [[3, 1, 2], [4, 2, 2]],
     [[-1, 0, 1],[1, -1, -2]],
     [[3, 2, 2],  [4, 4, 3]],
     [[2, 2, 1],  [3, 1, 3]]
    ])
Y = np.array(
    [[[2, 3, 1, 2, 1],
      [2, 2, 2, 0, 0],
      [3, 4, 0, 1, -1]],
     [[1, 4, 3, 2, 2],
      [4, 1, 1, 4, -3],
      [4, 1, 0, 3, 0]]])
R = np.dot(X, Y)
print("X.shape: ", X.shape, "   X.ndim: ", X.ndim)
print("Y.shape: ", Y.shape, "   Y.ndim: ", Y.ndim)
print("R.shape: ",     R.shape, "R.ndim: ", R.ndim)
print("\nThe result array R:\n")
print(R)

X.shape:  (4, 2, 3)    X.ndim:  3
Y.shape:  (2, 3, 5)    Y.ndim:  3
R.shape:  (4, 2, 2, 5) R.ndim:  4

The result array R:

[[[[ 14  19   5   8   1]
   [ 15  15  10  16   3]]

  [[ 18  24   8  10   2]
   [ 20  20  14  22   2]]]


 [[[  1   1  -1  -1  -2]
   [  3  -3  -3   1  -2]]

  [[ -6  -7  -1   0   3]
   [-11   1   2  -8   5]]]


 [[[ 16  21   7   8   1]
   [ 19  16  11  20   0]]

  [[ 25  32  12  11   1]
   [ 32  23  16  33  -4]]]


 [[[ 11  14   6   5   1]
   [ 14  11   8  15  -2]]

  [[ 17  23   5   9   0]
   [ 19  16  10  19   3]]]]


# comparison operator

In [93]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([ [11, 102, 13], [201, 22, 203], [31, 32, 303] ])
A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [94]:
print(np.array_equal(A, B))
print(np.array_equal(A, A))

False
True


# Logical Operators

In [95]:
a = np.array([ [True, True], [False, False]])
b = np.array([ [True, False], [True, False]])
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[[ True  True]
 [ True False]]
[[ True False]
 [False False]]


# Applying Operators on Arrays with Different Shapes
## Broadcasting


### Under certain conditions, the smaller array is "broadcasted" in a way that it has the same shape as the larger array.

<img src="broadcasting_example_1.png" style="float: left; height: 16em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="broadcasting_example_2.png" style="float: left; height: 16em; margin-right: 1%; margin-bottom: 0.5em;">
<img src="broadcasting_example_3.png" style="float: left; height: 16em; margin-right: 1%; margin-bottom: 0.5em;">

In [96]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ]) # 3x3 1X3
B = np.array([1, 2, 3])
print("Multiplication with broadcasting: ")
print(A * B)
print("... and now addition with broadcasting: ")
print(A + B)

Multiplication with broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [97]:
B = np.array([[1, 2, 3],] * 3)
print(B)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [98]:
B = np.array([1, 2, 3])
'''
[[1],
[2],
[3]]
'''
#B [np.newaxis, :]
'''
[[1,2,3]]
'''
B[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [100]:
A * B[:, np.newaxis]

array([[11, 12, 13],
       [42, 44, 46],
       [93, 96, 99]])

In [102]:
np.mat(A)*np.mat(B[:, np.newaxis])

matrix([[ 74],
        [134],
        [194]])

In [103]:
A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [104]:
A[:, np.newaxis] * B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [ ]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
B = B[np.newaxis, :]
B = np.concatenate((B, B, B))
print("Multiplication: ")
print(A * B)
print("... and now addition again: ")
print(A + B)

In [108]:
B = np.tile(np.array([1, 2, 3]), (3, 1))
print(B)
# print("Multiplication: ")
# print(A * B)
# print("... and now addition again: ")
# print(A + B)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Flatten an array

In [109]:
A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])
Flattened_X = A.flatten()
print(Flattened_X)
print(A.flatten(order="C"))
print(A.flatten(order="F"))
print(A.flatten(order="A"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [110]:
print(A.ravel())
print(A.ravel(order="A"))
print(A.ravel(order="F"))
print(A.ravel(order="A"))
print(A.ravel(order="K"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [114]:
# reshape
# reshape(a, newshape, order='C')
X = np.array(range(24)).reshape((3,4,2))
# Y = X.reshape((3,4,2))
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [115]:
# Concatinating array
x = np.array([11,22])
y = np.array([18,7,6])
z = np.array([1,3,5])
c = np.concatenate((x,y,z))
print(c)

[11 22 18  7  6  1  3  5]


In [116]:
x = np.array(range(24))
x = x.reshape((3,4,2))
y = np.array(range(100,124))
y = y.reshape((3,4,2))
z = np.concatenate((x,y))
print(z)

[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]]

 [[100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[116 117]
  [118 119]
  [120 121]
  [122 123]]]


In [126]:
x = np.array([[11,22]])
y = np.array([[18,7,6],
              [8,17,6]])
c = np.concatenate((y,x.T), axis=1)
print(c)

[[18  7  6 11]
 [ 8 17  6 22]]


In [127]:
# Adding new dimension
x = np.array([2,5,18,14,4])
y = x[:, np.newaxis]
print(y)

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


In [128]:
# Vector stacking
A = np.array([3, 4, 5])
B = np.array([1,9,0])
print(np.row_stack((A, B)))
print(np.column_stack((A, B)))
np.shape(A)

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


(3,)

In [129]:
A = np.array([[3, 4, 5],
              [1, 9, 0],
              [4, 6, 8]])
np.column_stack((A, A, A))

array([[3, 4, 5, 3, 4, 5, 3, 4, 5],
       [1, 9, 0, 1, 9, 0, 1, 9, 0],
       [4, 6, 8, 4, 6, 8, 4, 6, 8]])

In [130]:
np.dstack((A, A, A))

array([[[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]],

       [[1, 1, 1],
        [9, 9, 9],
        [0, 0, 0]],

       [[4, 4, 4],
        [6, 6, 6],
        [8, 8, 8]]])