In [14]:
'''
The default pseudo-random number generator of the random module was designed with the focus on modelling and simulation, 
not on security. So, you shouldn't generate sensitive information such as passwords, secure tokens, session keys and 
similar things by using random
'''
import random
random_number = random.random()
print(random_number)

0.26744772515411064


In [15]:
# It uses sources which are provided by the operating system. This will be /dev/urandom on Unix and CryptGenRandom on windows
from random import SystemRandom
crypto = SystemRandom()
print(crypto.random())

0.14382081728949747


In [18]:
import numpy as np

list_of_random_floats = np.random.random(100)
# print(list_of_random_floats)
sum_of_values = list_of_random_floats.sum()
print(sum_of_values)
normalized_values = list_of_random_floats / sum_of_values
print(normalized_values.sum())

46.670418321471246
1.0


In [25]:
#Random Integers
li = [ random.randint(1, 6) for _ in range(10) ]
print(li)

outcome = np.random.randint(1, 7, size=10)
print(outcome)
# print(np.dtype(outcome))

[5, 1, 3, 4, 1, 3, 6, 6, 5, 4]
[4 3 3 2 5 6 6 5 1 2]


In [29]:
A = np.array([2,3,6,7])
B = np.array([4,8,9,2])
print(A*B)
print('\n')
print(A/B)
print('\n')
print(A-B)
print('\n')
print(A+B)
print('\n')
print(A**2)
print('\n')
print(A%2)

[ 8 24 54 14]


[0.5        0.375      0.66666667 3.5       ]


[-2 -5 -3  5]


[ 6 11 15  9]


[ 4  9 36 49]


[0 1 0 1]


In [32]:
possible_destinations = ["Berlin", "Hamburg", "Munich", 
                         "Amsterdam", "London", "Paris", 
                         "Zurich", "Heidelberg", "Strasbourg", 
                         "Augsburg", "Milan", "Rome"]
print(random.choice(possible_destinations))
print(random.choice("RAJAT"))
print(np.random.choice(possible_destinations))

Berlin
A
Augsburg


In [40]:
print(np.random.choice(possible_destinations, size=(5,4)))
print('\n')
# how to prevent multiple occurences
print(np.random.choice(possible_destinations, size=(3, 4), replace=False))

[['Berlin' 'Milan' 'Augsburg' 'Augsburg']
 ['Paris' 'Heidelberg' 'Hamburg' 'Zurich']
 ['Strasbourg' 'Hamburg' 'Amsterdam' 'Amsterdam']
 ['Amsterdam' 'Amsterdam' 'Amsterdam' 'Berlin']
 ['Zurich' 'Zurich' 'Hamburg' 'Hamburg']]


[['Augsburg' 'London' 'Rome' 'Strasbourg']
 ['Milan' 'Hamburg' 'Paris' 'Zurich']
 ['Heidelberg' 'Amsterdam' 'Berlin' 'Munich']]


In [41]:
x = np.random.random_sample((3, 4))
print(x)

[[0.94083112 0.7381447  0.08434946 0.88457383]
 [0.23687447 0.74677063 0.63253786 0.24164893]
 [0.46664698 0.92801381 0.94125485 0.67071678]]


In [42]:
# print continuous distribution
a = -3.4
b = 5.9
A = (b - a) * np.random.random_sample((3, 4)) + a # 0 , 9 = 0+-3.4 , 9-3.4 = -3.4,5.9
print(A)

[[ 3.61636363  5.52269563  0.86534416 -2.01022478]
 [-2.2847315  -1.52925811  3.54320793 -0.82505568]
 [ 2.83442299  1.00730383 -2.1692411   0.26377121]]


In [43]:
# in random module 
print(random.sample(range(1, 50), 6))

[26, 39, 4, 1, 14, 20]


In [44]:
#weighted random choice 
professions = ["scientist", 
               "philosopher", 
               "engineer", 
               "priest", 
               "programmer"]
probabilities = [0.2, 0.05, 0.5, 0.15, 0.1]
np.random.choice(professions, p=probabilities)

'priest'

In [47]:
from collections import Counter
c = Counter()
for _ in range(1000):
    profession = np.random.choice(professions, p=probabilities)
    c[profession] += 1
    
print(c)
s = sum(c.values())
for el in c:
    c[el] /= s
print(c)

Counter({'engineer': 510, 'scientist': 201, 'priest': 140, 'programmer': 102, 'philosopher': 47})
Counter({'engineer': 0.51, 'scientist': 0.201, 'priest': 0.14, 'programmer': 0.102, 'philosopher': 0.047})


In [50]:
import random
random.seed(23)
for _ in range(10):
    print(random.randint(1, 10), end=", ")
    
print("\nLet's create the same random numbers again:")
random.seed(23)
for _ in range(10):
    print(random.randint(1, 10), end=", ")

5, 2, 1, 10, 5, 7, 7, 9, 6, 3, 
Let's create the same random numbers again:
5, 2, 1, 10, 5, 7, 7, 9, 6, 3, 