## Boolean masking of array

In [59]:
import numpy as np
A = np.array([4, 7, 3, 4, 2, 8])
print(A == 4)

[ True False False  True False False]


In [60]:
print(A < 5)

[ True False  True  True  True False]


In [61]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])
print(B>=42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


In [63]:
import numpy as np
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

In [65]:
#  It is called fancy indexing, if arrays are indexed by using boolean or 
#  integer arrays (masks). The result will be a copy and not a view.
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,7,2,8,6,9,5])
R = C[A<=5]
print(R)

[123 190 100]


In [67]:
print(C[0], C[1])
C[[0, 2, 3, 1, 4, 1]]

123 188


array([123, 190,  99, 188,  77, 188])

In [74]:
# Extract from the array np.array([3,4,6,10,24,89,45,43,46,99,100]) with Boolean masking all the number

# which are not divisible by 3
A = np.array([3,4,6,10,24,89,45,43,46,99,100])
print(A[A%3!=0])

# which are divisible by 5
print(A[A%5==0])

# which are divisible by 3 and 5
print(A[(A%5==0) & (A%3==0)])

# which are divisible by 3 and set them to 42
A[A%3==0] = 42
print(A)

[  4  10  89  43  46 100]
[ 10  45 100]
[45]
[ 42   4  42  10  42  89  42  43  46  42 100]


In [75]:
a = np.array([[0, 2, 3, 0, 1],
              [1, 0, 0, 7, 0],
              [5, 0, 0, 1, 0]])
print(a.nonzero())

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 4, 0, 3, 0, 3], dtype=int64))


In [76]:
print(np.transpose(a.nonzero()))

[[0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [2 0]
 [2 3]]


In [77]:
a[a.nonzero()] # a[a[0,1], a[]]

array([2, 3, 1, 1, 7, 5, 1])

In [78]:
np.count_nonzero(a)

7

In [81]:
np.flatnonzero(a)

array([ 1,  2,  4,  5,  8, 10, 13], dtype=int64)

In [82]:
np.nonzero(np.ravel(a))

(array([ 1,  2,  4,  5,  8, 10, 13], dtype=int64),)

# Matrix Arithmetic

In [95]:
A = np.matrix( ((1,2), (5, -1)), dtype=int)
B = np.matrix( ((1,2), (5, -1)), dtype=int)
print(type(A))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [96]:
A = np.array([[2,3],[3,4]])
B = np.array([[2,3],[3,4]])
print(A*B)
print(np.mat(A) * np.mat(B))
print(type(A))

[[ 4  9]
 [ 9 16]]
[[13 18]
 [18 25]]
<class 'numpy.ndarray'>


In [85]:
print(A/B)
print('\n')
print(A*B)
print('\n')
print(A-B)
print('\n')
print(A+B)
print('\n')
print(A*2)

[[1. 1.]
 [1. 1.]]


[[11  0]
 [ 0 11]]


[[0 0]
 [0 0]]


[[ 2  4]
 [10 -2]]


[[ 2  4]
 [10 -2]]


In [102]:
x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], np.int32)
np.savetxt("test.txt", x)

In [100]:
np.savetxt("test2.txt", x, fmt="%04d", delimiter=" :-) ")

In [103]:
y = np.loadtxt("test.txt")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [105]:
y = np.loadtxt("test2.txt", delimiter=" :-) ", usecols=(0,2))
print(y)

[[1. 3.]
 [4. 6.]
 [7. 9.]]
